// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GetReq.proto

#ifndef PROTOBUF_GetReq_2eproto__INCLUDED
#define PROTOBUF_GetReq_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_GetReq_2eproto();
void protobuf_AssignDesc_GetReq_2eproto();
void protobuf_ShutdownFile_GetReq_2eproto();

class GetReqMessage;

// ===================================================================

class GetReqMessage : public ::google::protobuf::Message {
 public:
  GetReqMessage();
  virtual ~GetReqMessage();

  GetReqMessage(const GetReqMessage& from);

  inline GetReqMessage& operator=(const GetReqMessage& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GetReqMessage& default_instance();

  void Swap(GetReqMessage* other);

  // implements Message ----------------------------------------------

  GetReqMessage* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GetReqMessage& from);
  void MergeFrom(const GetReqMessage& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string imgID = 1;
  inline bool has_imgid() const;
  inline void clear_imgid();
  static const int kImgIDFieldNumber = 1;
  inline const ::std::string& imgid() const;
  inline void set_imgid(const ::std::string& value);
  inline void set_imgid(const char* value);
  inline void set_imgid(const char* value, size_t size);
  inline ::std::string* mutable_imgid();
  inline ::std::string* release_imgid();
  inline void set_allocated_imgid(::std::string* imgid);

  // required int32 width = 2;
  inline bool has_width() const;
  inline void clear_width();
  static const int kWidthFieldNumber = 2;
  inline ::google::protobuf::int32 width() const;
  inline void set_width(::google::protobuf::int32 value);

  // required int32 height = 3;
  inline bool has_height() const;
  inline void clear_height();
  static const int kHeightFieldNumber = 3;
  inline ::google::protobuf::int32 height() const;
  inline void set_height(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:GetReqMessage)
 private:
  inline void set_has_imgid();
  inline void clear_has_imgid();
  inline void set_has_width();
  inline void clear_has_width();
  inline void set_has_height();
  inline void clear_has_height();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* imgid_;
  ::google::protobuf::int32 width_;
  ::google::protobuf::int32 height_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_GetReq_2eproto();
  friend void protobuf_AssignDesc_GetReq_2eproto();
  friend void protobuf_ShutdownFile_GetReq_2eproto();

  void InitAsDefaultInstance();
  static GetReqMessage* default_instance_;
};
// ===================================================================


// ===================================================================

// GetReqMessage

// required string imgID = 1;
inline bool GetReqMessage::has_imgid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GetReqMessage::set_has_imgid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GetReqMessage::clear_has_imgid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void GetReqMessage::clear_imgid() {
  if (imgid_ != &::google::protobuf::internal::kEmptyString) {
    imgid_->clear();
  }
  clear_has_imgid();
}
inline const ::std::string& GetReqMessage::imgid() const {
  return *imgid_;
}
inline void GetReqMessage::set_imgid(const ::std::string& value) {
  set_has_imgid();
  if (imgid_ == &::google::protobuf::internal::kEmptyString) {
    imgid_ = new ::std::string;
  }
  imgid_->assign(value);
}
inline void GetReqMessage::set_imgid(const char* value) {
  set_has_imgid();
  if (imgid_ == &::google::protobuf::internal::kEmptyString) {
    imgid_ = new ::std::string;
  }
  imgid_->assign(value);
}
inline void GetReqMessage::set_imgid(const char* value, size_t size) {
  set_has_imgid();
  if (imgid_ == &::google::protobuf::internal::kEmptyString) {
    imgid_ = new ::std::string;
  }
  imgid_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* GetReqMessage::mutable_imgid() {
  set_has_imgid();
  if (imgid_ == &::google::protobuf::internal::kEmptyString) {
    imgid_ = new ::std::string;
  }
  return imgid_;
}
inline ::std::string* GetReqMessage::release_imgid() {
  clear_has_imgid();
  if (imgid_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = imgid_;
    imgid_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void GetReqMessage::set_allocated_imgid(::std::string* imgid) {
  if (imgid_ != &::google::protobuf::internal::kEmptyString) {
    delete imgid_;
  }
  if (imgid) {
    set_has_imgid();
    imgid_ = imgid;
  } else {
    clear_has_imgid();
    imgid_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// required int32 width = 2;
inline bool GetReqMessage::has_width() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void GetReqMessage::set_has_width() {
  _has_bits_[0] |= 0x00000002u;
}
inline void GetReqMessage::clear_has_width() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void GetReqMessage::clear_width() {
  width_ = 0;
  clear_has_width();
}
inline ::google::protobuf::int32 GetReqMessage::width() const {
  return width_;
}
inline void GetReqMessage::set_width(::google::protobuf::int32 value) {
  set_has_width();
  width_ = value;
}

// required int32 height = 3;
inline bool GetReqMessage::has_height() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void GetReqMessage::set_has_height() {
  _has_bits_[0] |= 0x00000004u;
}
inline void GetReqMessage::clear_has_height() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void GetReqMessage::clear_height() {
  height_ = 0;
  clear_has_height();
}
inline ::google::protobuf::int32 GetReqMessage::height() const {
  return height_;
}
inline void GetReqMessage::set_height(::google::protobuf::int32 value) {
  set_has_height();
  height_ = value;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_GetReq_2eproto__INCLUDED
